name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish dotpaste/dotpaste.csproj -c Release -o build
    - name: Upload to server
      uses: ErSoul/scp_uploader@v1.0
      with:
        host: ${{vars.SSH_HOST}}
        username: ${{secrets.SSH_USER}}
        key: ${{secrets.SSH_KEY}}
        source: ./build/*
        target: /srv/dotpaste
        after: systemctl --user restart dotpaste