# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotpaste

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish dotpaste/dotpaste.csproj -c Release -o build
    - name: SCP Uploader
      uses: ersoul/scp_uploader@v0.1
      with:
        host: ${{vars.SSH_HOST}}
        username: ${{secrets.SSH_USER}}
        key: ${{secrets.SSH_KEY}}
        source: ./build/*
        target: /srv/dotpaste
        after: systemctl --user restart dotpaste